---
## Install the build dependencies
- name: Install dependencies
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl-devel
      - expat-devel
      - gettext-devel
      - openssl-devel
      - zlib-devel
      - gcc
      - perl-ExtUtils-MakeMaker

## Create the folder we'll use to extract Git
- name: Create extraction folder
  file:
    path: "/tmp/git-{{ git_version }}"
    state: directory
    mode: 0755

## Extract the Git source
- name: Extract Git
  unarchive:
    src: "{{ git_source_url }}"
    dest: "/tmp/git-{{ git_version }}"
    remote_src: yes
    # Don't create a first-level-folder
    extra_opts: [--strip-components=1]

## Build Git
- name: Build Git from source
  command: "make prefix={{ git_install_dir }} all"
  args:
    chdir: "/tmp/git-{{ git_version }}"
  when: installed_git_version != git_version

## Install Git
- name: Install Git from source
  become: true
  command: "make prefix={{ git_install_dir }} install"
  args:
    chdir: "/tmp/git-{{ git_version }}"
  when: installed_git_version != git_version

## Configure the user environment to have the Git path
- name: Configure environment
  become: true
  lineinfile:
    path: /etc/bashrc
    line: "export PATH={{ git_install_dir }}/bin:$PATH"
  when: installed_git_version != git_version
